### ISSUE TITLE
Share more utilities written in Python

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Py-Utils#1]
Do you know of any utilities that could be helpful to other people? Contribute them here!

For more information about the hacktoberfest and how you can get a free shirt, check out https://hacktoberfest.digitalocean.com.

**Comment by marcosstefani** [comment]
I want to work on this Issue.

**Comment by Lonami** [comment]
Go ahead! Everyone can, as there are *a lot* of handy utilities around.

**Comment by marcosstefani** [comment]
https://github.com/LonamiWebs/Py-Utils/pull/4
